remote_theme: sighingnow/jekyll-gitbook

title: XgPageBuilder
description: A powerful page builder package for Laravel
url: https://xgeniousllc.github.io
baseurl: /xgpagebuilder

# Author
author: Xgenious

# GitBook theme settings
toc:
  enabled: true
  h_min: 1
  h_max: 3

# Search
search:
  enabled: true

# Sharing
sharing:
  all: false

# Footer
footer:
  enabled: true
  content: 'Copyright &copy; Xgenious. Distributed under the MIT License.'

# Links
links:
  - name: GitHub
    url: https://github.com/XgeniousLLC/xgpagebuilder
  - name: Packagist  
    url: https://packagist.org/packages/xgenious/xgpagebuilder
